general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Dim both monitors after 2.5 minutes
listener {
    timeout = 150

    on-timeout = sh -c '
        ddcutil --bus 1 --sleep-multiplier 2 setvcp 10 20 --noverify;
        ddcutil --bus 4 --sleep-multiplier 2 setvcp 10 20 --noverify
    '

    on-resume = sh -c '
        ddcutil --bus 1 --sleep-multiplier 2 setvcp 10 100 --noverify;
        ddcutil --bus 4 --sleep-multiplier 2 setvcp 10 100 --noverify
    '
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn monitors off after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Suspend after 15 minutes
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
