#!/usr/bin/env bash

# wait until hyprpaper is available
#until hyprctl hyprpaper listloaded >/dev/null 2>&1; do
#    sleep 0.2
#done

WALLPAPER_DIR="$HOME/Pictures/wallpapers"

# get current loaded wallpaper filename
CURRENT_WALL=$(hyprctl hyprpaper listloaded | head -n1 | awk '{print $NF}')

# pick a random wallpaper that's not the current
WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n1)

# unload all preloaded wallpapers
hyprctl hyprpaper unload all

# preload the new one
hyprctl hyprpaper preload "$WALLPAPER"

# set it as wallpaper for all monitors
hyprctl hyprpaper wallpaper ",$WALLPAPER,cover"

splash = false
