#!/usr/bin/env bash
#preload = $HOME/Pictures/wallpapers/i7gacbaq3aie1.jpeg
#wallpaper =  , $HOME/Pictures/wallpapers/i7gacbaq3aie1.jpeg
#


#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/wallpapers/"

# get current loaded wallpaper file name
CURRENT_WALL=$(hyprctl hyprpaper listloaded | head -n1)

# choose random wallpaper except the current one
WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# unload the previous (optional but recommended)
hyprctl hyprpaper unload all

# preload new wallpaper
hyprctl hyprpaper preload "$WALLPAPER"

# actually set it (all monitors)
hyprctl hyprpaper wallpaper ",$WALLPAPER"

