#!/usr/bin/env bash

# Rofi dmenu mode, -i make search case-insensitive, -l is the number of line
rofi_command() {
  rofi -dmenu -i -config "$HOME/.config/rofi/power.rasi"
}

shutdown="󰐥 | Shutdown"
reboot=" | Restart"
lock=" | Lock"
suspend="󰤄 | Suspend"
logout="󰍂 | Logout"

options="$shutdown\n$reboot\n$logout\n$suspend\n$lock"

chosen="$(echo -e "$options" | rofi_command)"
echo "$chosen"

case "$chosen" in
"$shutdown")
  systemctl poweroff
  ;;

"$reboot")
  systemctl reboot
  ;;

"$lock")
  swaylock -f
  # Or if you're using hyprlock:
  # hyprlock
  ;;

"$suspend")
  mpc -q pause
  amixer set Master mute
  systemctl suspend
  ;;

"$logout")
  uwsm stop
  ;;
esac
